# Generated by Django 6.0.4 on 2026-04-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='currentStamina',
            field=models.IntegerField(default=15),
        ),
    ]
