version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000" # Expose backend port for direct access if needed
    volumes:
      - sqlite_data:/app/data

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
