# Generated by Django 6.0.3 on 2026-03-17 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterDropTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('xp', models.IntegerField(default=0)),
                ('bossesDefeated', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('currentStamina', models.IntegerField(default=10)),
                ('townLevel', models.IntegerField(default=1)),
                ('townXP', models.IntegerField(default=0)),
                ('inventory', models.JSONField(default=list)),
                ('equipped', models.JSONField(default=dict)),
                ('activePotions', models.JSONField(default=list)),
                ('unlockedCreatures', models.JSONField(default=list)),
                ('activeQuest', models.JSONField(blank=True, null=True)),
                ('shopStock', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
